x = (1, 2, 3)
y = (4, 5, 6)
lst_A = (x + y)
lst_B = (x + y)
print('"A"')
print("first =", lst_A[:3])
print("second =", lst_A[2:5])
lst_A = list(lst_A)
print("result =", lst_A)
print('"B"')
t_result = (lst_A, tuple(reversed(x)), lst_B[-2:1:-1])
print("t_result =", t_result)
print('"C"')
print(t_result[0][2])
print(t_result[1][2])
print(t_result[2][2])
